### PR TITLE
Adding google analytics

### PR DESCRIPTION
**Pull request by Bratalix**

### CODE REVIEW

**Comment by BarryThePenguin** [comment]
Thanks @Bratalix 

Take a look at the focustas.org repo, there's an example there of setting up ga with URL change tracking

https://github.com/NewFrontDoor/focustas.org/blob/master/src/pages/_document.tsx
https://github.com/NewFrontDoor/focustas.org/blob/master/src/components/analytics.tsx

It might need additional packages installed too. I'll see if I can find a list

**Comment by Bratalix** [comment]
Is there an issue with this implementation? Luke requested gtag and it is the same as the implementation for St Kilda as well (excluding the typescript change).

Are there benefits to using Analytics over GTM that I should be aware of?

**Comment by BarryThePenguin** [comment]
> Is there an issue with this implementation?

No issue with using GTM. GTM has more uses than just collecting analytics. In that case it's preferable over GA.

[`autotrack`](https://www.npmjs.com/package/autotrack) has tracking for url changes built in. It would be nice to not have to rely on `next/router` for that information.

Can I do some research and get back to you?

**Comment by Bratalix** [comment]
> [`autotrack`](https://www.npmjs.com/package/autotrack) has tracking for url changes built in. It would be nice to not have to rely on `next/router` for that information.

That's a good point.

> Can I do some research and get back to you?

Of course

**Comment by BarryThePenguin** [comment]
There is this article.. https://support.google.com/tagmanager/answer/7679322

I'll put something together for focustas.org

Looks like GA isn't currently working on focustas.org 🤔 Looking at the history, it stopped around the 5th August? The last deploy was 24 June.. so not sure of the cause yet..

**Review by BarryThePenguin — APPROVED** [review]
👍 Thanks! Sorry it took so long 😓

**Pull request merged**
